-- MySQL Script generated by MySQL Workbench
-- Thu Nov  8 20:16:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydata
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydata` ;

-- -----------------------------------------------------
-- Schema mydata
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydata` DEFAULT CHARACTER SET utf8 ;
USE `mydata` ;

-- -----------------------------------------------------
-- Table `mydata`.`hibernate_sequence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`hibernate_sequence` ;

CREATE TABLE IF NOT EXISTS `mydata`.`hibernate_sequence` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`made_wedding_halls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`made_wedding_halls` ;

CREATE TABLE IF NOT EXISTS `mydata`.`made_wedding_halls` (
  `hall_hno` INT NOT NULL AUTO_INCREMENT,
  `hall_name` VARCHAR(50) NOT NULL,
  `hall_location` VARCHAR(100) NOT NULL,
  `hall_person` INT NOT NULL,
  `hall_price` INT NOT NULL,
  `hall_thema` VARCHAR(150) NOT NULL,
  `hall_contents` VARCHAR(250) NOT NULL,
  `hall_link` VARCHAR(25) NOT NULL,
  `hall_area` INT NOT NULL,
  PRIMARY KEY (`hall_hno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`made_wedding_halls_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`made_wedding_halls_img` ;

CREATE TABLE IF NOT EXISTS `mydata`.`made_wedding_halls_img` (
  `ino` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(200) NOT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `hno` INT NOT NULL,
  `area` INT NOT NULL,
  `link` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ino`, `fullName`, `hno`),
  CONSTRAINT `fk_made_wedding_halls_img_hno`
    FOREIGN KEY (`hno`)
    REFERENCES `mydata`.`made_wedding_halls` (`hall_hno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_made_wedding_halls_img_idx` ON `mydata`.`made_wedding_halls_img` (`hno` ASC);


-- -----------------------------------------------------
-- Table `mydata`.`made_wedding_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`made_wedding_member` ;

CREATE TABLE IF NOT EXISTS `mydata`.`made_wedding_member` (
  `mwno` INT NOT NULL AUTO_INCREMENT,
  `mwid` VARCHAR(20) NOT NULL,
  `mwpw` VARCHAR(50) NOT NULL,
  `mwname` VARCHAR(20) NOT NULL,
  `mwmobile` VARCHAR(11) NOT NULL,
  `mwbirth` VARCHAR(6) NOT NULL,
  `mwregdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`mwno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `mwid_UNIQUE` ON `mydata`.`made_wedding_member` (`mwid` ASC);


-- -----------------------------------------------------
-- Table `mydata`.`made_wedding_step1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`made_wedding_step1` ;

CREATE TABLE IF NOT EXISTS `mydata`.`made_wedding_step1` (
  `memberID` VARCHAR(20) NOT NULL,
  `list_day` VARCHAR(150) NOT NULL,
  `list_week` VARCHAR(150) NOT NULL,
  `list_area` VARCHAR(150) NOT NULL,
  `list_etc` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`memberID`),
  CONSTRAINT `step1_memberID`
    FOREIGN KEY (`memberID`)
    REFERENCES `mydata`.`made_wedding_member` (`mwid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`made_wedding_step2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`made_wedding_step2` ;

CREATE TABLE IF NOT EXISTS `mydata`.`made_wedding_step2` (
  `memberID` VARCHAR(20) NOT NULL,
  `list_day` VARCHAR(150) NOT NULL,
  `list_week` VARCHAR(150) NOT NULL,
  `list_area` VARCHAR(150) NOT NULL,
  `list_etc` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`memberID`),
  CONSTRAINT `step2_memberID`
    FOREIGN KEY (`memberID`)
    REFERENCES `mydata`.`made_wedding_member` (`mwid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`made_wedding_step3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`made_wedding_step3` ;

CREATE TABLE IF NOT EXISTS `mydata`.`made_wedding_step3` (
  `memberID` VARCHAR(20) NOT NULL,
  `list_day` VARCHAR(150) NOT NULL,
  `list_week` VARCHAR(150) NOT NULL,
  `list_area` VARCHAR(150) NOT NULL,
  `list_etc` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`memberID`),
  CONSTRAINT `step3_memberID`
    FOREIGN KEY (`memberID`)
    REFERENCES `mydata`.`made_wedding_member` (`mwid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`made_wedding_step4`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`made_wedding_step4` ;

CREATE TABLE IF NOT EXISTS `mydata`.`made_wedding_step4` (
  `memberID` VARCHAR(20) NOT NULL,
  `list_day` VARCHAR(150) NOT NULL,
  `list_week` VARCHAR(150) NOT NULL,
  `list_area` VARCHAR(150) NOT NULL,
  `list_etc` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`memberID`),
  CONSTRAINT `step4_memberID`
    FOREIGN KEY (`memberID`)
    REFERENCES `mydata`.`made_wedding_member` (`mwid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`made_wedding_studios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`made_wedding_studios` ;

CREATE TABLE IF NOT EXISTS `mydata`.`made_wedding_studios` (
  `studio_hno` INT NOT NULL AUTO_INCREMENT,
  `studio_name` VARCHAR(50) NOT NULL,
  `studio_location` VARCHAR(100) NOT NULL,
  `studio_person` INT NOT NULL,
  `studio_price` INT NOT NULL,
  `studio_thema` VARCHAR(150) NOT NULL,
  `studio_contents` VARCHAR(250) NOT NULL,
  `studio_link` VARCHAR(25) NOT NULL,
  `studio_area` INT NOT NULL,
  PRIMARY KEY (`studio_hno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`made_wedding_studios_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`made_wedding_studios_img` ;

CREATE TABLE IF NOT EXISTS `mydata`.`made_wedding_studios_img` (
  `ino` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(200) NOT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `hno` INT NOT NULL,
  `area` INT NOT NULL,
  `link` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ino`, `fullName`, `hno`),
  CONSTRAINT `fk_made_wedding_studios_img_hno`
    FOREIGN KEY (`hno`)
    REFERENCES `mydata`.`made_wedding_studios` (`studio_hno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_made_wedding_studios_img_hno_idx` ON `mydata`.`made_wedding_studios_img` (`hno` ASC);


-- -----------------------------------------------------
-- Table `mydata`.`re_tbl_board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`re_tbl_board` ;

CREATE TABLE IF NOT EXISTS `mydata`.`re_tbl_board` (
  `bno` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `writer` VARCHAR(50) NULL DEFAULT NULL,
  `origin` INT NULL DEFAULT '0',
  `depth` INT NULL DEFAULT '0',
  `seq` INT NULL DEFAULT '0',
  `regdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `viewcnt` INT NULL DEFAULT '0',
  `uno` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`bno`, `uno`),
  CONSTRAINT `fk_user_uno`
    FOREIGN KEY (`uno`)
    REFERENCES `mydata`.`tbl_user` (`uno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_user_uno_idx` ON `mydata`.`re_tbl_board` (`uno` ASC);


-- -----------------------------------------------------
-- Table `mydata`.`tbl_attach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_attach` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_attach` (
  `fullName` VARCHAR(150) NOT NULL,
  `bno` INT NOT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`fullName`, `bno`),
  CONSTRAINT `fk_tbl_attach`
    FOREIGN KEY (`bno`)
    REFERENCES `mydata`.`re_tbl_board` (`bno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tbl_attach_idx` ON `mydata`.`tbl_attach` (`bno` ASC);


-- -----------------------------------------------------
-- Table `mydata`.`tbl_board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_board` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_board` (
  `bno` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `writer` VARCHAR(45) NULL DEFAULT NULL,
  `regdate` TIMESTAMP NULL DEFAULT NULL,
  `viewcnt` INT NULL DEFAULT '0',
  PRIMARY KEY (`bno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`tbl_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_comment` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_comment` (
  `cno` INT NOT NULL AUTO_INCREMENT,
  `bno` INT NOT NULL,
  `commentText` VARCHAR(100) NOT NULL,
  `commentAuth` VARCHAR(45) NOT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uno` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`cno`, `bno`, `uno`),
  CONSTRAINT `fk_board`
    FOREIGN KEY (`bno`)
    REFERENCES `mydata`.`re_tbl_board` (`bno`),
  CONSTRAINT `fk_tbl_user_uno`
    FOREIGN KEY (`uno`)
    REFERENCES `mydata`.`tbl_user` (`uno`))
ENGINE = InnoDB
AUTO_INCREMENT = 95
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_board` ON `mydata`.`tbl_comment` (`bno` ASC);

CREATE INDEX `fk_tbl_user_uno_idx` ON `mydata`.`tbl_comment` (`uno` ASC);


-- -----------------------------------------------------
-- Table `mydata`.`tbl_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_member` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_member` (
  `userid` VARCHAR(50) NOT NULL,
  `userpw` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `regdate` DATE NULL DEFAULT NULL,
  `updatedate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`tbl_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_user` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_user` (
  `uno` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(50) NOT NULL,
  `upw` VARCHAR(50) NOT NULL,
  `uname` VARCHAR(100) NOT NULL,
  `upoint` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`uno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `uid_UNIQUE` ON `mydata`.`tbl_user` (`uid` ASC);


-- -----------------------------------------------------
-- Table `mydata`.`tbl_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`tbl_message` ;

CREATE TABLE IF NOT EXISTS `mydata`.`tbl_message` (
  `mno` INT NOT NULL AUTO_INCREMENT,
  `targetid` VARCHAR(50) NOT NULL,
  `sender` VARCHAR(50) NOT NULL,
  `message` TEXT NOT NULL,
  `opendate` TIMESTAMP NULL DEFAULT NULL,
  `senddate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`mno`, `sender`, `targetid`),
  CONSTRAINT `fk_usersender`
    FOREIGN KEY (`sender`)
    REFERENCES `mydata`.`tbl_user` (`uid`),
  CONSTRAINT `fk_usertarget`
    FOREIGN KEY (`targetid`)
    REFERENCES `mydata`.`tbl_user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_usertarget` ON `mydata`.`tbl_message` (`targetid` ASC);

CREATE INDEX `fk_usersender` ON `mydata`.`tbl_message` (`sender` ASC);


-- -----------------------------------------------------
-- Table `mydata`.`test_board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`test_board` ;

CREATE TABLE IF NOT EXISTS `mydata`.`test_board` (
  `bno` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NOT NULL,
  `writer` VARCHAR(50) NOT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `viewcnt` INT NULL DEFAULT '0',
  PRIMARY KEY (`bno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`test_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`test_member` ;

CREATE TABLE IF NOT EXISTS `mydata`.`test_member` (
  `userid` VARCHAR(50) NOT NULL,
  `userpw` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydata`.`test_tbl_board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydata`.`test_tbl_board` ;

CREATE TABLE IF NOT EXISTS `mydata`.`test_tbl_board` (
  `bno` BIGINT(20) NOT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `regdata` DATETIME NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `updatedata` DATETIME NULL DEFAULT NULL,
  `writer` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`bno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
